FROM registry.librechat.ai/danny-avila/librechat-dev-api:latest
COPY client/public/assets/logo.svg /app/client/public/assets/logo.svg
COPY client/public/assets/favicon-16x16.png /app/client/public/assets/favicon-16x16.png
COPY client/public/assets/favicon-32x32.png /app/client/public/assets/favicon-32x32.png
COPY client/public/assets/apple-touch-icon-180x180.png /app/client/public/assets/apple-touch-icon-180x180.png
COPY client/public/assets/icon-192x192.png /app/client/public/assets/icon-192x192.png
COPY client/public/assets/maskable-icon.png /app/client/public/assets/maskable-icon.png
